### ISSUE TITLE
Jenkins install at BLPD

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/turbo_seti#68]
This one will require some setup. To run long integration tests with large data we can't really use Travis, so would need to switch to Jenkins, (or run both in parallel).

**Comment by texadactyl** [comment]
@telegraphic 

1. I recently figured out how to force Travis to run long jobs with keep-alive console output using a pre-forked background job.
2. Last night, we moved on to Github Actions CI because of the long queuing times at Travis CI.

It is still true that we need to plan how to make more meaningful regression tests that use large data files or subsets thereof.

**Comment by texadactyl** [comment]
@telegraphic 
Is this issue still a concern after the move to Github Actions?
Not sure why integration tests need node blpd - data source?

**Comment by texadactyl** [comment]
If we find a large file with certain characteristics, we can generate a small-enough artificial file with ```dice``` and/or ```setigen``` that exhibits these characteristics.  Of course, that might not cover a case where the size itself gives rise to a characteristic.

It is a bit of work to be sure but I believe that test case construction this way covers most of our needs.
