### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/turbo_seti#75]
Currently only reporting 3% (likely just a config issue)!

**Comment by telegraphic** [comment]
Ok, fixed the issue causing 3% and we're now back to 49%. Still a lot of room to improve

**Comment by texadactyl** [comment]
One big gap in testing: we have very little if anything for the coverage of plot_event.py and plot_event_pipeline.py.

Currently, we have only one testing source file: test_turbo_seti.py.  Inside, test_plotting() was renamed so that it will not be called because there are parameter conflicts.  In any case, only one test is insufficient.

Proposal:
* Rip out test_plotting() from the existing file.
* One of the interns would supply a new source file with a set of plotting tests that supply good coverage.

**Comment by texadactyl** [comment]
As it were, instead of ripping out test_plotting() from the test_turbo_seti.py, I converted it to a specific direct call to make_waterfall_plots().

**Comment by texadactyl** [comment]
Gap was closed although now we have a coverage issue in Travis CI not supporting NVIDIA GPU.
